// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC35U39UPi6_bx0_XLR5jUlsRLym__aEus',
    appId: '1:599404561674:web:44e40de5822a571cc2a6f3',
    messagingSenderId: '599404561674',
    projectId: 'lead-form-85fe4',
    authDomain: 'lead-form-85fe4.firebaseapp.com',
    storageBucket: 'lead-form-85fe4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6qdNXVMoR1qyyOdFsS0vfGRtnivi9LLg',
    appId: '1:599404561674:android:ba63e3519a0c463cc2a6f3',
    messagingSenderId: '599404561674',
    projectId: 'lead-form-85fe4',
    storageBucket: 'lead-form-85fe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRiuxhDm-x-O9Syrh7o8uRZN_NmydGxHc',
    appId: '1:599404561674:ios:b232c963a8a7c727c2a6f3',
    messagingSenderId: '599404561674',
    projectId: 'lead-form-85fe4',
    storageBucket: 'lead-form-85fe4.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRiuxhDm-x-O9Syrh7o8uRZN_NmydGxHc',
    appId: '1:599404561674:ios:b232c963a8a7c727c2a6f3',
    messagingSenderId: '599404561674',
    projectId: 'lead-form-85fe4',
    storageBucket: 'lead-form-85fe4.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );
}
